"""update users model

Revision ID: c5511235c383
Revises: 8e42f2a9c6fc
Create Date: 2025-04-08 22:27:34.174809

"""

from typing import Sequence, Union

from alembic import op



# revision identifiers, used by Alembic.
revision: str = "c5511235c383"
down_revision: Union[str, None] = "8e42f2a9c6fc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "users", ["email"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    # ### end Alembic commands ###
